# Dynamic Environment Variables for Production!
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate rules
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Keep the security guard away for now
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration